import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Lusitana,
  Montserrat,
  Istok_Web,
  Inter,
} from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lusitana = Lusitana({
  weight: ['400', '700'],
  variable: "--font-lusitana",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: ['400', '500', '600', '700'],
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const istokWeb = Istok_Web({
  weight: ['400', '700'],
  variable: "--font-istok-web",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lusitana.variable} ${montserrat.variable} ${istokWeb.variable} ${inter.variable} antialiased`}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
